@startuml
title "业务时序图"

client --> server:   makeId
activate server

server --> IDBufferManager: handler -> getIdByBizTag
activate IDBufferManager
    IDBufferManager -> IDBufferManager: isMake IDBufferSegment?
    IDBufferManager -> IDBufferSegment: factory!
    IDBufferSegment -> IDBuffer: factory
    IDBuffer -> DBGen
    DBGen -> IDBufferManager: finish
    IDBufferManager -> IDBufferSegment: getIDBufferSegmentByBizTag
    activate IDBufferSegment
        IDBufferSegment -> IDBuffer:  Select Current IDBuffer
        IDBuffer -> IDBufferSegment: finish 
        IDBufferSegment --> IDBuffer: flush
        IDBufferSegment -> IDBufferSegment: change  
        IDBufferSegment -> IDBuffer: is finish ?
        IDBuffer -> IDBufferSegment: finish 
        IDBufferSegment -> IDBufferSegment:wait ! 
        IDBufferSegment --> IDBufferSegment: finish ok 
            IDBufferSegment -> IDBuffer: getId
                activate IDBuffer
                activate Stats
                Stats --> IDBuffer: dig stats
                IDBuffer --> Stats: is flush Buffer? getCurrentPercent
                Stats --> IDBufferSegment: flush IDBuffer
                deactivate Stats
                destroy Stats

                IDBuffer->IDBuffer: getId with Buffer
                IDBuffer --> DBGen: getId
                DBGen --> IDBuffer: return id
            IDBuffer -> IDBufferSegment: return id
            deactivate IDBuffer
        IDBufferSegment -> IDBufferManager: return id
        deactivate IDBufferSegment
    IDBufferManager -> server: reeturn id
server -> client : handler -> getId
deactivate server

@enduml
